// Generated by Wrangler on Sat Apr 13 2024 13:03:25 GMT+0300 (Восточная Европа, летнее время)
// by running `wrangler types`

interface Env {
	XATA_API_KEY: string;
	XATA_BRANCH: string;
	XATA_DATABASE_URL: string;
	AI: unknown;
}
